### ISSUE TITLE
Replace occurences of deprecated `db_query` API

### ISSUE THREAD

**Issue by dregad** [chelmertz/mantis-triggerclose#5]
In MantisBT 1.3, the `db_query()` function will be removed from the API (see mantisbt/mantisbt#128).
The following occurences have been found in this plugin; they should be replaced
by `db_query_bound()` calls

```
TriggerClose/TriggerCloseApi.php:231:       $query = db_query($sql);

```

**Comment by chelmertz** [comment]
@dregad Perhaps you can work against the mantis-organization's fork instead? It's here: https://github.com/mantisbt-plugins/TriggerClose

I'll archive this repository for now. Good luck!
