### ISSUE TITLE
The inactivity test doesn't work correctly

### ISSUE THREAD

**Issue by yannrouillard** [chelmertz/mantis-triggerclose#6]
Hi Chelmertz,

We are currently testing the TriggerClose plugin to automatically close bugs in the resolved state for some time and we noticed that the inactivity test doesn't work correctly. Our bug are closed quickly after entering the "resolved status" even if they have been active recently.

The plugin in fact closes bugs that has been opened for "after_seconds" seconds and not that have been active for "after_seconds" seconds.

The sql request used selects the history entries which are older than "current_time - after_seconds())", but at bug opened a long time ago will always have such entries, even if it had been very active recently.

Yann

**Comment by chelmertz** [comment]
@yannrouillard  Perhaps you can work against the mantis-organization's fork instead? It's here: https://github.com/mantisbt-plugins/TriggerClose

I'll archive this repository for now. Good luck!
